# Exercise configuration file

agent_base: "template_pytorch" # currently not implemented, the agent base image to use
ws_dir: "solution" # directory that contains the code
agent_run_cmd: "run_agent.sh" # the script in "launchers" to run the agent with
ros: false
challenge: aido-LFV-sim-validation
lab_dir: .
